# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
darklua = "seaofvoices/darklua@0.16.0"
lune = "lune-org/lune@0.9.3"
# rojo = "rojo-rbx/rojo@6.2.0"